//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DARMEX_AGROEntities : DbContext
    {
        public DARMEX_AGROEntities()
            : base("name=DARMEX_AGROEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<table_costumer> table_costumer { get; set; }
        public virtual DbSet<table_produk> table_produk { get; set; }
        public virtual DbSet<table_produk_detail> table_produk_detail { get; set; }
        public virtual DbSet<table_transaksi> table_transaksi { get; set; }
        public virtual DbSet<table_user> table_user { get; set; }
    
        public virtual ObjectResult<SelectAllTransaksi_Result> SelectAllTransaksi(Nullable<int> transaksi_id)
        {
            var transaksi_idParameter = transaksi_id.HasValue ?
                new ObjectParameter("transaksi_id", transaksi_id) :
                new ObjectParameter("transaksi_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectAllTransaksi_Result>("SelectAllTransaksi", transaksi_idParameter);
        }
    }
}
