//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_produk_detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public table_produk_detail()
        {
            this.table_transaksi = new HashSet<table_transaksi>();
        }
    
        public int produk_detail_id { get; set; }
        public int produk_id { get; set; }
        public string produk_detail_name { get; set; }
        public Nullable<decimal> price_per_item { get; set; }
        public Nullable<decimal> discount { get; set; }
    
        public virtual table_produk table_produk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<table_transaksi> table_transaksi { get; set; }
    }
}
